sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
before_install:
- gem install bundler -v 2.0.1
- rm Gemfile.lock
script: bundle exec rake test
notifications:
  slack:
    rooms:
      secure: gAmGsKm7wt0Qn/1eP9Kk/md/Dy9/eXjjPpxUhkOB9C17aJUbHWWtJ1HKDpkdOyp1lM3IjJuDHpE927XoOFgcQ0jFBZVrHfrbrW4Abt8kRMZTEqeY1OZWiuDo/ArrEon6PUXXEFeXpMzdnU9HN2jPQ2Nd2FhpW7lBkWTvOg1U2L6yrb5xNQ6XwT8wNzlVu2BqZ/b/s114SpdQ/efCOnT/vXb4dPUGaYjgopmNcuR1rtITGLMV51thLPy/1bNYl2+OtJUOXOWLEb4dSxuwYWwvzRoeIzh+Hu62Ml5Ih0l/KVfdwQDbRKjgGCp7fmOqZfxheMl7h4eq/0CVQSWA7z21qymhDwLcJ16fY39ijEKWnAwI5BuaMFM8SWl9xsO04i/XP7+GrGFhhopGuqLSQhFc/V/FIFgKz3C6VxY5IIOZ4NHazJP1uMrpQNBPvKbt4trPtlVKPt7KsfgJE/pJISpLhLes/KNalHUpKaNtxEg/JmLCTzjj6KCRLV0yT6Hi1isQtDn13GUtgriI2MLk1mxMBp9bICTIIJO49jcFT+j6XcAWPdawPBTvZlb4w4G0CyYDs/EDPSvbME2L0tDExPHMaUYWEL11vMki1vgsv8KrfOalQtzFgmyyqADIFH0ALkJAD6VY0YooZT2ymKj1uMCCx7UTtOCbpTrhWJhljunHTIs=
